name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_subdomain: ${{ vars.SUBDOMAIN }}
      TF_VAR_bucket: ${{ vars.BUCKET }}
      TF_VAR_region: ${{ vars.REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init \
          -backend-config="bucket=${{ vars.TF_STATE_BACKEND_BUCKET }}" \
          -backend-config="key=${{ vars.TF_STATE_BACKEND_KEY }}" \
          -backend-config="region=${{ vars.REGION }}" \
          -backend-config="dynamodb_table=${{ vars.TF_STATE_LOCK }}" \
          -backend-config="encrypt=true"
          terraform apply -auto-approve