name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_domain_name: ${{ env.TF_VAR_domain_name }}
      TF_VAR_subdomain: ${{ env.TF_VAR_subdomain }}
      TF_VAR_bucket: ${{ env.TF_VAR_bucket }}
      TF_VAR_tf_state_backend_bucket: ${{ env.TF_VAR_tf_state_backend_bucket }}
      TF_VAR_tf_state_backend_key: ${{ env.TF_VAR_tf_state_backend_key }}
      TF_VAR_tf_state_lock: ${{ env.TF_VAR_tf_state_lock }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve